import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>のりやん食堂</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header></header>
        <nav>
          <div>
            <div>LOGO</div>
            <hr />
            <div>
              ご予約・お問い合わせ
              <button>00-0000-0000</button>
            </div>
            <ul>
              <li>お知らせ</li>
              <li>メニュー</li>
              <li>アクセス</li>
            </ul>
            <hr />
            <div>
              <div>INSTA</div>
              <div>ACCESS</div>
              {/* ACCESS -> Calculate the distance from where I am to the restaurant */}
            </div>
          </div>
        </nav>
        <section>{/* MAIN IMAGE */}</section>
        <section>{/* お知らせ */}</section>
        <section>
          {/* メニュー */}
          <article>{/* おすすめ */}</article>
          <article>{/* ドリンク */}</article>
          <article>{/* おすすめ */}</article>
        </section>
        <section>{/* アクセス */}</section>
        <section></section>
        <div></div>
        <footer></footer>
      </main>
    </>
  );
}
